spring:
  application:
    name: customer-service

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:liquibase/changelog/master.yml
    default-schema: ${POSTGRES_SCHEMA:customer}

server:
  port: 8084
